Repository sebgroup/frontend-tools, pull requests merged in 2020-06, with the labels that each got.

#123 refactor(openapi-generator): split mock from base
  package-lock.json
  package.json
  src/openapiGenerator/mockGenerator/formatResponse.ts
  src/openapiGenerator/mockGenerator/generateData.ts
  src/openapiGenerator/mockGenerator/mockGenerator.ts
  src/openapiGenerator/openapiGenerator.ts
  src/openapiGenerator/templates/typescript-axios/baseApi.mustache
  webpack/webpack.config.bin.js
  webpack/webpack.config.tool.js
Labels: 🚧 Refactor

#140 feat(formvalidator): validate fields that have value only
  src/FormValidator/FormValidator.test.ts
  src/FormValidator/FormValidator.ts
Labels: 🔨 Enhancement

#150 feat(openapi-generator): mock generator swagger examples
  src/openapiGenerator/mockGenerator/formatResponse.ts
Labels: 🔨 Enhancement

#145 fix(openapigenerator): fix code generator template
  package.json
  src/openapiGenerator/getSubcommand.ts
  src/openapiGenerator/mockGenerator/mockGenerator.ts
  src/openapiGenerator/openapiGenerator.ts
  src/openapiGenerator/options/batchOptions.ts
  src/openapiGenerator/options/configHelpOptions.ts
  src/openapiGenerator/options/customOptions.ts
  src/openapiGenerator/options/generateOptions.ts
  src/openapiGenerator/options/listOptions.ts
  src/openapiGenerator/options/metaOptions.ts
  src/openapiGenerator/options/option.type.ts
  src/openapiGenerator/options/validateOptions.ts
  src/openapiGenerator/templates/typescript-axios/baseApi.mustache
  src/openapiGenerator/templates/typescript-axios/modelGeneric.mustache
Labels: 🐛 Bug

#141 feat(openapi-generator): adds typescript-angular template
  src/openapiGenerator/options/customOptions.ts
  src/openapiGenerator/templates/typescript-angular/api.service.mustache
  src/openapiGenerator/templates/typescript-angular/configuration.mustache
  src/openapiGenerator/templates/typescript-angular/model.mustache
  src/openapiGenerator/templates/typescript-angular/models.mustache
Labels: 🔨 Enhancement

#151 feat(openapi-generator): allow user to disable mock generation
  src/openapiGenerator/openapiGenerator.ts
  src/openapiGenerator/options/customOptions.ts
Labels: 🔨 Enhancement

#157 fix(deepcopy): fix deepcopy symbol
  src/deepCopy/deepCopy.test.ts
  src/deepCopy/deepCopy.ts
Labels: 🐛 Bug

#153 fix(openapi-generator): fix openapi generator baseurl
  src/openapiGenerator/openapiGenerator.ts
  src/openapiGenerator/options/customOptions.ts
  src/openapiGenerator/templates/typescript-axios/apiInner.mustache
  src/openapiGenerator/templates/typescript-axios/baseApi.mustache
Labels: 🐛 Bug

#158 fix(openapi-generator): fixes dates in mock generator
  src/openapiGenerator/mockGenerator/generateData.ts
Labels: 🐛 Bug
