Repository sebgroup/frontend-tools, pull requests merged in 2020-08, with the labels that each got.

#174 fix(openapi-generator): fix header issue
  src/openapiGenerator/openapiGenerator.ts
  src/openapiGenerator/templates/ts-angular/api.mustache
  src/openapiGenerator/templates/ts-angular/apiInner.mustache
  src/openapiGenerator/templates/ts-angular/baseApi.mustache
  src/openapiGenerator/templates/typescript-axios/api.mustache
  src/openapiGenerator/templates/typescript-axios/apiInner.mustache
  src/openapiGenerator/templates/typescript-axios/baseApi.mustache
Labels: 🐛 Bug

#175 Release: OpenAPI bug fixes
  package-lock.json
  src/openapiGenerator/openapiGenerator.ts
  src/openapiGenerator/templates/ts-angular/api.mustache
  src/openapiGenerator/templates/ts-angular/apiInner.mustache
  src/openapiGenerator/templates/ts-angular/baseApi.mustache
  src/openapiGenerator/templates/typescript-axios/api.mustache
  src/openapiGenerator/templates/typescript-axios/apiInner.mustache
  src/openapiGenerator/templates/typescript-axios/baseApi.mustache
Labels: 🚀 Release

#177 fix(openapi-generator): fix simulate data bug
  src/openapiGenerator/templates/ts-angular/baseApi.mustache
Labels: 🐛 Bug

#178 Release: minor bug fix in OpenAPI utility
  src/openapiGenerator/templates/ts-angular/baseApi.mustache
Labels: 🚀 Release

#179 fix(isphonenumber): fix isphonenumber validation to match 4-15 digits
  src/FormValidator/FormValidator.test.ts
  src/isPhoneNumber/isPhoneNumber.test.ts
  src/isPhoneNumber/isPhoneNumber.ts
Labels: 🐛 Bug

#180 New release: update isPhoneNumber utility
  src/FormValidator/FormValidator.test.ts
  src/isPhoneNumber/isPhoneNumber.test.ts
  src/isPhoneNumber/isPhoneNumber.ts
Labels: 🚀 Release

#185 Refactor/formatdate without moment
  README.md
  package-lock.json
  package.json
  src/formatDate/formatDate.test.ts
  src/formatDate/formatDate.ts
  webpack/webpack.config.tool.js
Labels: 🚧 Refactor

#181 Refactor/removing moment as dependency
  README.md
  package-lock.json
  package.json
  src/FormValidator/FormValidator.ts
  src/clearTime/clearTime.test.ts
  src/dateDiff/dateDiff.test.ts
  src/dateDiff/dateDiff.ts
  src/formatDate/formatDate.test.ts
  src/formatDate/formatDate.ts
  src/isDateAfter/isDateAfter.ts
  src/isDateBefore/index.ts
  src/isDateBefore/isDateBefore.test.ts
  src/isDateBefore/isDateBefore.ts
  src/isSameDate/isSameDate.ts
  src/isValidDate/index.ts
  src/isValidDate/isValidDate.test.ts
  src/isValidDate/isValidDate.ts
  src/modifyDate/modifyDate.test.ts
  src/modifyDate/modifyDate.ts
  src/toDate/toDate.test.ts
  src/toDate/toDate.ts
  src/toLocalDateString/toLocalDateString.ts
  webpack/webpack.config.tool.js
Labels: 📦 Dependencies, 🔨 Enhancement, 🚧 Refactor

#184 fix(openapi-generator): fix template return type
  src/openapiGenerator/mockGenerator/formatResponse.ts
  src/openapiGenerator/templates/ts-angular/apiInner.mustache
  src/openapiGenerator/templates/typescript-axios/apiInner.mustache
Labels: 🐛 Bug

#186 New release: Removed moment
  README.md
  package-lock.json
  package.json
  src/FormValidator/FormValidator.ts
  src/clearTime/clearTime.test.ts
  src/dateDiff/dateDiff.test.ts
  src/dateDiff/dateDiff.ts
  src/formatDate/formatDate.test.ts
  src/formatDate/formatDate.ts
  src/isDateAfter/isDateAfter.ts
  src/isDateBefore/index.ts
  src/isDateBefore/isDateBefore.test.ts
  src/isDateBefore/isDateBefore.ts
  src/isSameDate/isSameDate.ts
  src/isValidDate/index.ts
  src/isValidDate/isValidDate.test.ts
  src/isValidDate/isValidDate.ts
  src/modifyDate/modifyDate.test.ts
  src/modifyDate/modifyDate.ts
  src/openapiGenerator/mockGenerator/formatResponse.ts
  src/openapiGenerator/templates/ts-angular/apiInner.mustache
  src/openapiGenerator/templates/typescript-axios/apiInner.mustache
  src/toDate/toDate.test.ts
  src/toDate/toDate.ts
  src/toLocalDateString/toLocalDateString.ts
  webpack/webpack.config.tool.js
Labels: 🚀 Release

#187 fix(openapi-generator): fix promise return
  src/openapiGenerator/templates/ts-angular/apiInner.mustache
  src/openapiGenerator/templates/typescript-axios/apiInner.mustache
Labels: 🐛 Bug

#191 Refactor/update release directory
  .github/workflows/build-check.yml
  .github/workflows/publish.yml
  README.md
  bin/generate-api
  package-lock.json
  package.json
  rollup.config.js
  scripts/indexer.js
  scripts/pre-release.js
  src/formatDate/formatDate.test.ts
  src/formatDate/formatDate.ts
  src/index.js
  src/index.ts
  src/openapiGenerator/generatorList.ts
  src/openapiGenerator/getSubcommand.ts
  src/openapiGenerator/index.ts
  src/openapiGenerator/mockGenerator/formatResponse.ts
  src/openapiGenerator/mockGenerator/generateData.ts
  src/openapiGenerator/mockGenerator/mockGenerator.ts
  src/openapiGenerator/openapiGenerator.ts
  src/openapiGenerator/options/batchOptions.ts
  src/openapiGenerator/options/configHelpOptions.ts
  src/openapiGenerator/options/customOptions.ts
  src/openapiGenerator/options/generateOptions.ts
  src/openapiGenerator/options/listOptions.ts
  src/openapiGenerator/options/metaOptions.ts
  src/openapiGenerator/options/option.type.ts
  src/openapiGenerator/options/validateOptions.ts
  src/openapiGenerator/templates/ts-angular/api.mustache
  src/openapiGenerator/templates/ts-angular/apiInner.mustache
  src/openapiGenerator/templates/ts-angular/baseApi.mustache
  src/openapiGenerator/templates/ts-angular/modelGeneric.mustache
  src/openapiGenerator/templates/ts-angular/modelIndex.mustache
  src/openapiGenerator/templates/typescript-angular/api.service.mustache
  src/openapiGenerator/templates/typescript-angular/configuration.mustache
  src/openapiGenerator/templates/typescript-angular/model.mustache
  src/openapiGenerator/templates/typescript-angular/models.mustache
  src/openapiGenerator/templates/typescript-axios/api.mustache
  src/openapiGenerator/templates/typescript-axios/apiInner.mustache
  src/openapiGenerator/templates/typescript-axios/baseApi.mustache
  src/openapiGenerator/templates/typescript-axios/modelGeneric.mustache
  src/openapiGenerator/templates/typescript-axios/modelIndex.mustache
  stats.html
  tsconfig.d.json
  tsconfig.json
  webpack.config.js
  webpack/webpack.config.bin.js
  webpack/webpack.config.tool.js
Labels: 🚧 Refactor

#193 Refactor/use rollup summary plugin
  package-lock.json
  package.json
  rollup.config.js
Labels: 🚧 Refactor

#192 Release: BREAKING CHANGES
  .github/workflows/build-check.yml
  .github/workflows/publish.yml
  README.md
  bin/generate-api
  package-lock.json
  package.json
  rollup.config.js
  scripts/indexer.js
  scripts/pre-release.js
  src/formatDate/formatDate.test.ts
  src/formatDate/formatDate.ts
  src/index.js
  src/index.ts
  src/modifyDate/modifyDate.test.ts
  src/modifyDate/modifyDate.ts
  src/openapiGenerator/generatorList.ts
  src/openapiGenerator/getSubcommand.ts
  src/openapiGenerator/index.ts
  src/openapiGenerator/mockGenerator/formatResponse.ts
  src/openapiGenerator/mockGenerator/generateData.ts
  src/openapiGenerator/mockGenerator/mockGenerator.ts
  src/openapiGenerator/openapiGenerator.ts
  src/openapiGenerator/options/batchOptions.ts
  src/openapiGenerator/options/configHelpOptions.ts
  src/openapiGenerator/options/customOptions.ts
  src/openapiGenerator/options/generateOptions.ts
  src/openapiGenerator/options/listOptions.ts
  src/openapiGenerator/options/metaOptions.ts
  src/openapiGenerator/options/option.type.ts
  src/openapiGenerator/options/validateOptions.ts
  src/openapiGenerator/templates/ts-angular/api.mustache
  src/openapiGenerator/templates/ts-angular/apiInner.mustache
  src/openapiGenerator/templates/ts-angular/baseApi.mustache
  src/openapiGenerator/templates/ts-angular/modelGeneric.mustache
  src/openapiGenerator/templates/ts-angular/modelIndex.mustache
  src/openapiGenerator/templates/typescript-angular/api.service.mustache
  src/openapiGenerator/templates/typescript-angular/configuration.mustache
  src/openapiGenerator/templates/typescript-angular/model.mustache
  src/openapiGenerator/templates/typescript-angular/models.mustache
  src/openapiGenerator/templates/typescript-axios/api.mustache
  src/openapiGenerator/templates/typescript-axios/apiInner.mustache
  src/openapiGenerator/templates/typescript-axios/baseApi.mustache
  src/openapiGenerator/templates/typescript-axios/modelGeneric.mustache
  src/openapiGenerator/templates/typescript-axios/modelIndex.mustache
  stats.html
  tsconfig.d.json
  tsconfig.json
  webpack.config.js
  webpack/webpack.config.bin.js
  webpack/webpack.config.tool.js
Labels: 🚀 Release
