Repository sebgroup/frontend-tools, pull requests merged in 2020-04, with the labels that each got.

#74 chore: update dependencies and enhance config
  README.md
  jest.config.js
  package-lock.json
  package.json
Labels: dependencies

#87 feat(isprimitive): new isprimitive utility
  package-lock.json
  src/index.js
  src/isPrimitive/index.ts
  src/isPrimitive/isPrimitive.test.ts
  src/isPrimitive/isPrimitive.ts
Labels: 🔨 Enhancement

#88 fix(tocurrency): fix tocurrency showdecimals invalid implementation
  src/toCurrency/toCurrency.test.ts
  src/toCurrency/toCurrency.ts
Labels: 🐛 Bug

#100 Feature/generate api
  bin/generate-api
  package-lock.json
  package.json
  src/openapiGenerator/generatorList.ts
  src/openapiGenerator/getSubcommand.ts
  src/openapiGenerator/index.ts
  src/openapiGenerator/openapiGenerator.ts
  src/openapiGenerator/options/batchOptions.ts
  src/openapiGenerator/options/configHelpOptions.ts
  src/openapiGenerator/options/customOptions.ts
  src/openapiGenerator/options/generateOptions.ts
  src/openapiGenerator/options/listOptions.ts
  src/openapiGenerator/options/metaOptions.ts
  src/openapiGenerator/options/option.type.ts
  src/openapiGenerator/options/validateOptions.ts
  src/openapiGenerator/templates/typescript-axios/api.mustache
  src/openapiGenerator/templates/typescript-axios/apiInner.mustache
  src/openapiGenerator/templates/typescript-axios/baseApi.mustache
  src/openapiGenerator/templates/typescript-axios/modelGeneric.mustache
  src/openapiGenerator/templates/typescript-axios/modelIndex.mustache
  webpack.config.js
  webpack/webpack.config.bin.js
  webpack/webpack.config.tool.js
Labels: 🔨 Enhancement

#102 release: new release with generator
  bin/generate-api
  package-lock.json
  package.json
  src/openapiGenerator/generatorList.ts
  src/openapiGenerator/getSubcommand.ts
  src/openapiGenerator/index.ts
  src/openapiGenerator/openapiGenerator.ts
  src/openapiGenerator/options/batchOptions.ts
  src/openapiGenerator/options/configHelpOptions.ts
  src/openapiGenerator/options/customOptions.ts
  src/openapiGenerator/options/generateOptions.ts
  src/openapiGenerator/options/listOptions.ts
  src/openapiGenerator/options/metaOptions.ts
  src/openapiGenerator/options/option.type.ts
  src/openapiGenerator/options/validateOptions.ts
  src/openapiGenerator/templates/typescript-axios/api.mustache
  src/openapiGenerator/templates/typescript-axios/apiInner.mustache
  src/openapiGenerator/templates/typescript-axios/baseApi.mustache
  src/openapiGenerator/templates/typescript-axios/modelGeneric.mustache
  src/openapiGenerator/templates/typescript-axios/modelIndex.mustache
  webpack.config.js
  webpack/webpack.config.bin.js
  webpack/webpack.config.tool.js
Labels: 🔨 Enhancement

#106 fix(openapigenerator): fix apiinner mustache file
  src/openapiGenerator/openapiGenerator.ts
  src/openapiGenerator/templates/typescript-axios/apiInner.mustache
  src/openapiGenerator/templates/typescript-axios/baseApi.mustache
Labels: 🐛 Bug
